mysite/urls.py
from django.conf import settings
from django.conf.urls import include , url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='news/')),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^admin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url
from news.views import ArticleListView
from news.views import ArticleDetailView
from news.views import article_create
from news.views import article_update
from . import views


urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='article_list'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^create/$', article_create, name='create'),
    url(r'^article/(?P<slug>[-\w]+)/edit$', article_update, name='update')
]

news/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify
from unidecode import unidecode
from django.core.urlresolvers import reverse



class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):
        return self.full_name

class Article(models.Model):
    headline = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True)
    image = models.ImageField(blank=True, null=True,
        height_field='height_field',
        width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE, null=True)
    pub_date = models.DateField('date published', default=datetime.now)
    pub_time = models.TimeField('time published', default=datetime.now)

    class Meta():
        ordering = ['-pub_date', '-pub_time']

    def __str__(self):
        return self.headline

    #def _get_unique_slug(self):
    #    slug = slugify(self.title)
    #    unique_slug = slug
    #    num = 1
    #    while Article.objects.filter(slug=unique_slug).exists():
    #        unique_slug = '{}-{}'.format(slug, num)
    #        num += 1
    #    return unique_slug


    def save(self):
        self.slug = slugify(unidecode(self.headline))
        super(Article, self).save()

    def get_absolute_url(self):
        return reverse('news:article_detail', kwargs={"slug": self.slug})

    def __unicode__(self):
        return self.headline

news/forms.py
from django import forms


from .models import Article


class ArticleForm(forms.ModelForm):
   class Meta():
    model = Article
    fields = [
    "headline",
    "content",
    "image",
    "reporter",
    ]

news/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
import logging

from news.models import Article
from .forms import ArticleForm


log = logging.getLogger(__name__)

class ArticleListView(ListView):

    model = Article

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class ArticleDetailView(DetailView):

    model = Article

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context



def article_create(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "article_create.html", context)


def article_update(request, slug):
    instance = get_object_or_404(Article, slug=slug)
    form = ArticleForm(request.POST or None, instance=instance)
    if form.is_valid():
        log.warn("Form valid")
        form.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "headline": instance.headline,
        "instance": instance,
        "form": form,
    }
    return render(request, "article_update.html", context)    

news/templates/article_create.html
<ul>
<head>
    <link rel="icon" href="favicon.ico">
    <title>{% block title %}Новини міста Дрогобич{% endblock %}</title>
<meta charset="utf-8">
<style type="text/css">
    body {
        color: #adff2f;
        background: url(http://html-templates.info/images/pages/140520040122.jpg)
    }
    A {
        color: #32cd32;
    }
    html { overflow-y: scroll }
   .block1 { 
    width: 200px; 
    padding: 5px; 
    float: left;
    background-position: left;
    }
   .block2 { 
    width: 400px; 
    padding: 5px;  
    float: center; 
    position: center; 
    } 
</style> 
</head>
<body>
<center>
<div class="block1">
<a href="{% url 'article-list' %}">Головна</a>
</div>
<div class="block2">
    <h1>Додати новину</h1>
<form method="POST">{% csrf_token %}
{{  form.as_p  }}
<input type='submit' value='Опублікувати' />
</form>
</div>
</center>
</body>
</ul>

news/templates/article_update.html
<ul>
<head>
    <title>{% block title %}Новини міста Дрогобич{% endblock %}</title>
<meta charset="utf-8">
<style type="text/css">
    body {
        color: #adff2f;
        background: url(http://html-templates.info/images/pages/140520040122.jpg)
    }
    A {
        color: #32cd32;
    }
    html { overflow-y: scroll }
   .block1 { 
    width: 200px; 
    padding: 5px; 
    float: left;
    background-position: left;
    }
   .block2 { 
    width: 400px; 
    padding: 5px;  
    float: center; 
    position: center; 
    } 
</style> 
</head>
<body>
<center>
<div class="block1">
<a href="{% url 'news:article_list' %}">Головна</a>
</div>
<div class="block2">
    <h1>Редагувати</h1>
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{  form.as_p  }}
<input type='submit' value='Опублікувати' />
</form>
</div>
</center>
</body>
</ul>

news/templates/news/article_detail.html
<head>
    <title>{% block title %}{{article.headline}}{% endblock %}</title>
<style type="text/css">
    body {
        color: #adff2f;
        background: url(http://html-templates.info/images/pages/140520040122.jpg)
    }
    A {
        color: #ffff00;
    }
    h1 {
        color:#32cd32;
    }
    html { overflow-y: scroll }
   .block1 { 
    width: 200px; 
    padding: 5px; 
    float: left;
    background-position: left;
    }
   .block2 { 
    width: 400px; 
    color
    padding: 5px;  
    float: center; 
    position: center; 
    } 
</style> 
</head>
<div id="a">
    <p><a href="{% url 'news:article_list' %}">Головна</a>
</div>
{% load staticfiles %}
<center>
<div style="block2">
<h1>{{ article.headline }}</h1>
{% if article.image %}
<img src='{{ article.image.url }}' class='img-responsive' />
{% endif %}
<p>{{ article.content }}</p>
<p>{{ article.reporter }}</p>
<p>Опубліковано {{ article.pub_time|time:"H:i"  }} {{ article.pub_date|date:"F j, Y" }}</p>
<p><a href="{% url 'news:update' slug=article.slug %}">Редагувати</a></p>
</div>
</center>

news/templates/news/article_list.html
<ul>
<head>
    <title>{% block title %}Новини міста Дрогобич{% endblock %}</title>
<meta charset="utf-8">
<style type="text/css">
    body {
        color: #adff2f;
        background: url(http://html-templates.info/images/pages/140520040122.jpg)
    }
    A {
        color: #32cd32;
    }
    html { overflow-y: scroll }
   .block1 { 
    width: 200px; 
    padding: 5px; 
    float: left;
    background-position: left;
    }
   .block2 { 
    width: 400px; 
    padding: 5px;  
    float: center; 
    position: center; 
    } 
</style> 
</head>



<body>
<div class="block1">
    <h1><a href="{% url 'news:create' %}">Додати новину</a></h1>
</div>
<center>
<div class="block2">
<h1>Усі Новини</h1>
{% for article in article_list %}
    <p><a href="{% url 'news:article_detail'  article.slug %}">"{{ article.headline }}"</a></p>
    <p>Автор {{ article.reporter.full_name }}</p>
    <p>Опубліковано {{ article.pub_time|time:"H:i"  }} {{ article.pub_date|date:"F j, Y" }}</p>
{% endfor %}
</div>
</center>
</body>
</ul>